"""
提示词模板
"""

from .templates import (
    USER_PROFILER_SYSTEM,
    USER_PROFILER_PROMPT,
    OPPORTUNITY_MINER_SYSTEM,
    OPPORTUNITY_MINER_PROMPT,
    ACTION_PLANNER_SYSTEM,
    ACTION_PLANNER_PROMPT,
    VALIDATOR_SYSTEM,
    VALIDATOR_PROMPT,
)

__all__ = [
    "USER_PROFILER_SYSTEM",
    "USER_PROFILER_PROMPT",
    "OPPORTUNITY_MINER_SYSTEM",
    "OPPORTUNITY_MINER_PROMPT",
    "ACTION_PLANNER_SYSTEM",
    "ACTION_PLANNER_PROMPT",
    "VALIDATOR_SYSTEM",
    "VALIDATOR_PROMPT",
]
